-- NorthStar Ontology Fix Migration
-- ---------------------------------
-- This migration supports the ontology correction discussed in /plan-ceo-review:
--
-- 1. Application no longer "belongs to" a single project. Instead, Project
--    INVESTS_IN Application, with the time dimension (fiscal_year) living on
--    the edge. This migration does NOT touch Neo4j — it only adds the PG
--    tables needed to support the new loader and the fuzzy alias system.
--
-- 2. For non-CMDB applications (apps in draw.io diagrams that do NOT match
--    any CMDB standard_id), we default to diagram-scoped hash ids to avoid
--    accidental merges. A fuzzy normalize + human review table (this file)
--    lets us reconcile these after the fact.
--
-- Runs automatically on Postgres container start (docker-entrypoint-initdb).
-- Idempotent — safe to re-run.

SET search_path TO northstar, public;

-- =============================================================================
-- App normalization cache (for fuzzy matching non-CMDB apps)
-- =============================================================================
-- Every :Application node with cmdb_linked=false gets one row here, computed
-- by scripts/generate_merge_candidates.py. The norm_key is the output of
-- app.services.name_normalize.normalize_name().
CREATE TABLE IF NOT EXISTS app_normalized_name (
    app_id          VARCHAR PRIMARY KEY,
    raw_name        VARCHAR NOT NULL,
    norm_key        VARCHAR NOT NULL,
    diagram_id      VARCHAR,
    first_seen_at   TIMESTAMP DEFAULT NOW(),
    last_seen_at    TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_app_norm_key ON app_normalized_name (norm_key);

-- =============================================================================
-- Pending merge candidates — generated by scripts/generate_merge_candidates.py
-- =============================================================================
-- Each row represents a group of X-prefixed app_ids that share the same
-- norm_key. A human reviewer decides merge vs keep_separate via /admin/aliases.
CREATE TABLE IF NOT EXISTS pending_app_merge (
    id              SERIAL PRIMARY KEY,
    norm_key        VARCHAR NOT NULL,
    candidate_ids   VARCHAR[] NOT NULL,        -- ['X3a7f...', 'X8b2c...']
    raw_names       VARCHAR[] NOT NULL,        -- ['订单系统', 'Order System']
    projects        VARCHAR[] NOT NULL,        -- ['LI2500001', 'LI2500073', ...]
    created_at      TIMESTAMP DEFAULT NOW(),
    reviewed_at     TIMESTAMP,
    decision        VARCHAR,                   -- NULL | 'merge' | 'keep_separate'
    decided_by      VARCHAR,
    canonical_id    VARCHAR,                   -- the winner when decision='merge'
    note            TEXT
);
CREATE INDEX IF NOT EXISTS idx_pending_merge_pending
    ON pending_app_merge (created_at DESC) WHERE decision IS NULL;
CREATE INDEX IF NOT EXISTS idx_pending_merge_norm_key
    ON pending_app_merge (norm_key);

-- =============================================================================
-- Confirmed aliases — applied by load_neo4j_from_pg.py on every run
-- =============================================================================
-- After a human decides merge=yes, we write one row per non-canonical id
-- mapping it to the canonical one. The loader reads this whole table at
-- startup and uses it to collapse X-ids in derive_app_id().
CREATE TABLE IF NOT EXISTS manual_app_aliases (
    alias_id        VARCHAR PRIMARY KEY,       -- the id to be replaced
    canonical_id    VARCHAR NOT NULL,          -- the id it maps to
    decided_at      TIMESTAMP DEFAULT NOW(),
    decided_by      VARCHAR,
    source_merge_id INT REFERENCES pending_app_merge(id),
    note            TEXT
);
CREATE INDEX IF NOT EXISTS idx_alias_canonical
    ON manual_app_aliases (canonical_id);
