-- NorthStar What's New infrastructure
-- -----------------------------------
-- Tracks the history of application snapshots and surfaces deltas between
-- loader runs, so the frontend /whats-new page can show "what changed since
-- last visit". Supports CEO plan Expansion 5.
--
-- Runs automatically on a fresh postgres volume (docker-entrypoint-initdb)
-- AND on every backend container start (via app.main.ensure_sql_migrations),
-- so existing volumes pick it up without manual psql.

SET search_path TO northstar, public;

-- =============================================================================
-- Application snapshot history — one row per (app_id, snapshot_at)
-- =============================================================================
-- Written by the loader at the END of each successful run. We compare the
-- latest two rows per app to detect status / description changes, and that
-- comparison becomes the diff feed.
--
-- The loader only INSERTs a new row when content_hash differs from the most
-- recent row for that app, so this table grows only on real change.
CREATE TABLE IF NOT EXISTS applications_history (
    id                  BIGSERIAL PRIMARY KEY,
    app_id              VARCHAR NOT NULL,
    snapshot_at         TIMESTAMP NOT NULL DEFAULT NOW(),
    loader_run_id       VARCHAR,                  -- nullable; a uuid the loader generates per run
    name                VARCHAR,
    status              VARCHAR,
    description         TEXT,
    cmdb_linked         BOOLEAN DEFAULT FALSE,
    content_hash        VARCHAR(64) NOT NULL      -- sha256(name|status|description|cmdb_linked)
);
CREATE INDEX IF NOT EXISTS idx_app_hist_app_id
    ON applications_history (app_id, snapshot_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_hist_snapshot_at
    ON applications_history (snapshot_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_hist_run
    ON applications_history (loader_run_id);

-- =============================================================================
-- Ingestion diff feed — append-only, one row per change event
-- =============================================================================
-- Generated by the loader after applications_history is written. For each
-- app touched in this run, we compare the two most recent rows and emit
-- whatever events apply. An entity_id is the app_id for app-level events and
-- a "src→tgt|type" composite for integration events.
--
-- The /api/whats-new endpoint reads this table to build the feed.
CREATE TABLE IF NOT EXISTS ingestion_diffs (
    id                  BIGSERIAL PRIMARY KEY,
    loader_run_id       VARCHAR,                   -- same as applications_history.loader_run_id
    detected_at         TIMESTAMP NOT NULL DEFAULT NOW(),
    diff_type           VARCHAR(40) NOT NULL,      -- app_added | app_status_changed | app_description_changed |
                                                    -- app_removed | integration_added | integration_removed
    entity_type         VARCHAR(20) NOT NULL,      -- 'application' | 'integration' | 'project'
    entity_id           TEXT NOT NULL,
    entity_name         TEXT,                      -- denormalized for display (app name etc.)
    fiscal_year         VARCHAR(10),
    old_value           JSONB,
    new_value           JSONB
);
CREATE INDEX IF NOT EXISTS idx_diffs_detected_at
    ON ingestion_diffs (detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_diffs_type
    ON ingestion_diffs (diff_type);
CREATE INDEX IF NOT EXISTS idx_diffs_run
    ON ingestion_diffs (loader_run_id);
CREATE INDEX IF NOT EXISTS idx_diffs_entity
    ON ingestion_diffs (entity_type, entity_id);
