-- 015_deployment.sql
-- Infrastructure deployment data mirrored 1:1 from infraops_dev on
-- 10.196.155.195:5432/dxp_data_analysis.
-- Original table structure preserved. Synced by scripts/sync_from_infraops.py.

SET search_path TO northstar, public;

-- Servers: VM + Physical machines (原表: Application_AllServer_MetaData)
CREATE TABLE IF NOT EXISTS ref_deployment_server (
    _id                         BIGINT,
    serial_number               TEXT,
    ip_address                  TEXT,
    operational_status          TEXT,
    uuid                        TEXT,
    customer                    TEXT,
    description                 TEXT,
    owner                       TEXT,
    phone                       TEXT,
    "appOwnerL3OrgName"         TEXT,
    "appOwnerL4OrgName"         TEXT,
    appowner_orgname            TEXT,
    "createdBy"                 TEXT,
    "createdAt"                 TEXT,
    "updatedBy"                 TEXT,
    "updatedAt"                 TEXT,
    source                      TEXT,
    first_discovered            TEXT,
    last_discovered             TEXT,
    hot_line                    TEXT,
    uid                         TEXT,
    awp_group_name              TEXT,
    "appOwnerL5OrgName"         TEXT,
    is_clouddb                  TEXT,
    gpu_info                    TEXT,
    is_discrete_gpu             TEXT,
    info_classification         TEXT,
    "usedSpace"                 TEXT,
    is_sync_phone               TEXT,
    dc_port_no                  TEXT,
    sc_port_no                  TEXT,
    "numNetPorts"               TEXT,
    iaas_network_port           TEXT,
    platform_uuid               TEXT,
    before_migration_uuid       TEXT,
    "tcoU"                      TEXT,
    gpu_model                   TEXT,
    gpu_num                     TEXT,
    dc_operational_status       TEXT,
    "decomissionedFrom"         TEXT,
    gpu_server_tco              TEXT,
    "App_deploy_extension"      TEXT,
    before_migration_uuid_2     TEXT,
    all_ip_address              TEXT,
    "other_IP"                  TEXT,
    "server_IP"                 TEXT,
    hm_ip                       TEXT,
    name                        TEXT,
    landscape                   TEXT,
    app_name                    TEXT,
    app_id                      TEXT,
    is_virtualized              TEXT,
    device_type                 TEXT,
    server_type                 TEXT,
    model_id                    TEXT,
    model_type                  TEXT,
    fqdn                        TEXT,
    vp_name                     TEXT,
    vmname                      TEXT,
    have_dr                     TEXT,
    dr_ip                       TEXT,
    is_dr_server                TEXT,
    "className"                 TEXT,
    os_version                  TEXT,
    "OS expiration_OS EOL"      TEXT,
    os_type                     TEXT,
    kernel                      TEXT,
    priority                    TEXT,
    support_group               TEXT,
    is_dmz                      TEXT,
    cpu_count                   TEXT,
    cpu_core_count              TEXT,
    cpu_name                    TEXT,
    ram                         TEXT,
    disk_space                  TEXT,
    wwpn                        TEXT,
    wwnn                        TEXT,
    connection_port             TEXT,
    dc_u                        TEXT,
    usage_duration              TEXT,
    network_port                TEXT,
    service_type                TEXT,
    "Account_id"                TEXT,
    delivery_at                 TEXT,
    vpc_subnet_id               TEXT,
    "chargingMethod"            TEXT,
    cost_center                 TEXT,
    purchase_date               TEXT,
    warranty_expiration         TEXT,
    "assetStatus"               TEXT,
    manufacturer                TEXT,
    "City"                      TEXT,
    location                    TEXT,
    u_server_rack               TEXT,
    u_position                  TEXT,
    is_budget_refresh           TEXT,
    budget_refresh_year         TEXT,
    dept                        TEXT,
    business_group              TEXT,
    expire_date                 TEXT,
    req_no                      TEXT,
    request_by                  TEXT,
    "vp_name_Alias"             TEXT,
    synced_at                   TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ref_deploy_server_app ON ref_deployment_server (app_id);
CREATE INDEX IF NOT EXISTS idx_ref_deploy_server_city ON ref_deployment_server ("City");
CREATE INDEX IF NOT EXISTS idx_ref_deploy_server_id ON ref_deployment_server (_id);

-- Containers (原表: Application_Container_MetaData)
CREATE TABLE IF NOT EXISTS ref_deployment_container (
    _id                         BIGINT,
    name                        TEXT,
    limit_cpu                   TEXT,
    limit_mem                   TEXT,
    owner                       TEXT,
    cluster_id                  TEXT,
    cluster_name                TEXT,
    description                 TEXT,
    app_id                      TEXT,
    cmdb_app                    TEXT,
    "project_createdAt"         TEXT,
    "project_updatedAt"         TEXT,
    application_time            TEXT,
    "chargingMethod"            TEXT,
    cost_center                 TEXT,
    project_id                  TEXT,
    operational_status          TEXT,
    phone                       TEXT,
    "appOwnerL3OrgName"         TEXT,
    "appOwnerL4OrgName"         TEXT,
    type                        TEXT,
    expire_date                 TEXT,
    sc_request_no               TEXT,
    applicant                   TEXT,
    synced_at                   TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ref_deploy_container_app ON ref_deployment_container (app_id);
CREATE INDEX IF NOT EXISTS idx_ref_deploy_container_id ON ref_deployment_container (_id);

-- Database instances (原表: Application_Server_DB_MetaData)
CREATE TABLE IF NOT EXISTS ref_deployment_database (
    _id                         BIGINT,
    name                        TEXT,
    db_instance_name            TEXT,
    app_id                      TEXT,
    app_name                    TEXT,
    used_for                    TEXT,
    short_description           TEXT,
    version                     TEXT,
    u_ha                        TEXT,
    ha_type                     TEXT,
    ha_role                     TEXT,
    "className"                 TEXT,
    host_name                   TEXT,
    customer                    TEXT,
    os_type                     TEXT,
    os_version                  TEXT,
    go_live_time                TEXT,
    u_data_owner_s              TEXT,
    owner                       TEXT,
    dba_backup                  TEXT,
    app_owner                   TEXT,
    function_owner              TEXT,
    u_db_size_in_mb             TEXT,
    u_host_type                 TEXT,
    sunset_time                 TEXT,
    u_db_license                TEXT,
    operational_status          TEXT,
    port                        TEXT,
    "virtual_iP"                TEXT,
    node_ip1                    TEXT,
    node_ip2                    TEXT,
    discovery_source            TEXT,
    last_discovered             TEXT,
    "updatedAt"                 TEXT,
    "updatedBy"                 TEXT,
    "createdAt"                 TEXT,
    "createdBy"                 TEXT,
    change_control              TEXT,
    u_reference_server          TEXT,
    u_secondary_server          TEXT,
    support_group               TEXT,
    "chargingMethod"            TEXT,
    cost_center                 TEXT,
    first_discovered            TEXT,
    app_group                   TEXT,
    "appOwnerL3OrgName"         TEXT,
    "appOwnerL4OrgName"         TEXT,
    "functionOwnerL3OrgName"    TEXT,
    "functionOwnerL4OrgName"    TEXT,
    "Acc_Pwd"                   TEXT,
    is_clouddb                  TEXT,
    req_no                      TEXT,
    service_ip                  TEXT,
    "userCount"                 TEXT,
    source                      TEXT,
    db_owner                    TEXT,
    usage_duration              TEXT,
    expired_time                TEXT,
    cluster_name                TEXT,
    manager_ip                  TEXT,
    synced_at                   TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ref_deploy_db_app ON ref_deployment_database (app_id);
CREATE INDEX IF NOT EXISTS idx_ref_deploy_db_id ON ref_deployment_database (_id);

-- Object Storage (原表: Application_ObjectStorage_MetaData)
CREATE TABLE IF NOT EXISTS ref_deployment_object_storage (
    _id                         BIGINT,
    name                        TEXT,
    owner                       TEXT,
    operational_status          TEXT,
    discovery_source            TEXT,
    customer                    TEXT,
    req_no                      TEXT,
    "createdBy"                 TEXT,
    is_dmz                      TEXT,
    expiration_date             TEXT,
    delivery_at                 TEXT,
    landscape                   TEXT,
    location                    TEXT,
    app_name                    TEXT,
    app_id                      TEXT,
    cluster_id                  TEXT,
    max_size                    TEXT,
    max_buckets                 TEXT,
    ops_storage_dbid            TEXT,
    endpoint                    TEXT,
    request_by                  TEXT,
    "createdAt"                 TEXT,
    "updatedBy"                 TEXT,
    "updatedAt"                 TEXT,
    source                      TEXT,
    "chargingMethod"            TEXT,
    cost_center                 TEXT,
    "decomissionedFrom"         TEXT,
    synced_at                   TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ref_deploy_oss_app ON ref_deployment_object_storage (app_id);
CREATE INDEX IF NOT EXISTS idx_ref_deploy_oss_id ON ref_deployment_object_storage (_id);

-- NAS Storage (原表: Application_NAS_MetaData)
CREATE TABLE IF NOT EXISTS ref_deployment_nas (
    _id                         BIGINT,
    name                        TEXT,
    "shareId"                   TEXT,
    path                        TEXT,
    source                      TEXT,
    discovery_source            TEXT,
    "shareMount"                TEXT,
    owner                       TEXT,
    request_by                  TEXT,
    "targetIp"                  TEXT,
    capacity                    TEXT,
    type                        TEXT,
    location                    TEXT,
    app_name                    TEXT,
    app_id                      TEXT,
    landscape                   TEXT,
    operational_status          TEXT,
    "chargingMethod"            TEXT,
    cost_center                 TEXT,
    "createdAt"                 TEXT,
    "isDmz"                     TEXT,
    req_no                      TEXT,
    expiration_date             TEXT,
    info_classification         TEXT,
    "isDoubleActive"            TEXT,
    delivery_at                 TEXT,
    "decomissionedFrom"         TEXT,
    synced_at                   TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ref_deploy_nas_app ON ref_deployment_nas (app_id);
CREATE INDEX IF NOT EXISTS idx_ref_deploy_nas_id ON ref_deployment_nas (_id);
