"""What's New feed — /api/whats-new/*

Serves the change feed generated by the loader (see
scripts/load_neo4j_from_pg.py#write_history_and_diffs). The frontend
/whats-new page and the cockpit widget both consume this endpoint.
"""
from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from typing import Any, Optional

from fastapi import APIRouter, Query

from app.models.schemas import ApiResponse
from app.services import pg_client

router = APIRouter(prefix="/api/whats-new", tags=["whats-new"])


def _row_to_diff(row: Any) -> dict:
    """asyncpg Record → dict, with JSONB fields decoded to dict."""
    d = dict(row)
    for k in ("old_value", "new_value"):
        v = d.get(k)
        if isinstance(v, str):
            try:
                d[k] = json.loads(v)
            except (ValueError, TypeError):
                pass
    return d


@router.get("/summary")
async def summary(
    since: Optional[str] = Query(None, description="ISO timestamp; counts only diffs detected since this time"),
    days: int = Query(7, ge=1, le=365, description="Fallback window if 'since' not provided"),
) -> ApiResponse:
    """Counts for the cockpit widget.

    Returns app/integration change counts for either:
      - the window from `since` → now (if `since` is given), OR
      - the last `days` days (default 7)
    """
    if since:
        try:
            since_dt = datetime.fromisoformat(since.replace("Z", "+00:00")).replace(tzinfo=None)
        except ValueError:
            since_dt = datetime.utcnow() - timedelta(days=days)
    else:
        since_dt = datetime.utcnow() - timedelta(days=days)

    rows = await pg_client.fetch(
        """
        SELECT diff_type, count(*) AS c
        FROM northstar.ingestion_diffs
        WHERE detected_at >= $1
        GROUP BY diff_type
        """,
        since_dt,
    )
    by_type: dict[str, int] = {r["diff_type"]: r["c"] for r in rows}

    latest_row = await pg_client.fetchrow(
        "SELECT MAX(detected_at) AS latest FROM northstar.ingestion_diffs"
    )
    latest: Optional[datetime] = latest_row["latest"] if latest_row else None

    total = sum(by_type.values())
    return ApiResponse(
        data={
            "since": since_dt.isoformat(),
            "total": total,
            "by_type": by_type,
            "latest_diff_at": latest.isoformat() if latest else None,
        }
    )


@router.get("/feed")
async def feed(
    limit: int = Query(50, ge=1, le=500),
    offset: int = Query(0, ge=0),
    diff_type: Optional[str] = Query(None),
    days: int = Query(90, ge=1, le=365, description="Only return diffs from last N days"),
) -> ApiResponse:
    """Paginated feed of diff events, newest first, grouped client-side."""
    window_start = datetime.utcnow() - timedelta(days=days)
    if diff_type:
        rows = await pg_client.fetch(
            """
            SELECT id, loader_run_id, detected_at, diff_type, entity_type,
                   entity_id, entity_name, fiscal_year, old_value, new_value
            FROM northstar.ingestion_diffs
            WHERE detected_at >= $1 AND diff_type = $2
            ORDER BY detected_at DESC, id DESC
            LIMIT $3 OFFSET $4
            """,
            window_start,
            diff_type,
            limit,
            offset,
        )
    else:
        rows = await pg_client.fetch(
            """
            SELECT id, loader_run_id, detected_at, diff_type, entity_type,
                   entity_id, entity_name, fiscal_year, old_value, new_value
            FROM northstar.ingestion_diffs
            WHERE detected_at >= $1
            ORDER BY detected_at DESC, id DESC
            LIMIT $2 OFFSET $3
            """,
            window_start,
            limit,
            offset,
        )

    total_row = await pg_client.fetchval(
        """
        SELECT count(*) FROM northstar.ingestion_diffs
        WHERE detected_at >= $1
        """
        + (" AND diff_type = $2" if diff_type else ""),
        *((window_start, diff_type) if diff_type else (window_start,)),
    )
    return ApiResponse(
        data={
            "total": total_row or 0,
            "rows": [_row_to_diff(r) for r in rows],
        }
    )


@router.get("/runs")
async def runs(limit: int = Query(20, ge=1, le=100)) -> ApiResponse:
    """Recent loader runs, with a count of diffs emitted by each."""
    rows = await pg_client.fetch(
        """
        SELECT loader_run_id,
               MIN(detected_at) AS started_at,
               count(*) AS diff_count
        FROM northstar.ingestion_diffs
        WHERE loader_run_id IS NOT NULL
        GROUP BY loader_run_id
        ORDER BY started_at DESC
        LIMIT $1
        """,
        limit,
    )
    return ApiResponse(data=[dict(r) for r in rows])
